kumuluzee:
  name: property-catalogue-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      disk-space-health-check:
        threshold: 100000000
#    checks:
#      data-source-health-check:
#        jndi-name: jdbc/PropertyCatalogueDS
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    web-instrumentation:
      - name: property-catalogue-endpoint
        url-pattern: /v1/properties/*

rest-config:
  endpoint-enabled: true
  healthy: true
  load-intensity: 45
